### ISSUE TITLE
[bug] LPP crashes WebUI when cache.json is missing or empty

### ISSUE THREAD

**Issue by Krabbalka** [Siberpone/lazy-pony-prompter#1]
[Using Google Translate]

After installation (via the web interface), A1111 stopped starting.

My actions:
1) Installed from the link
2) created "derpi" with an API key in ...lazy-pony-prompter/auth.

`venv "D:\123\stable-diffusion-webui-master\venv\Scripts\Python.exe"
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.6.0
Commit hash: <none>
Launching Web UI with arguments: --xformers
Loading weights [0f885597eb] from D:\123\stable-diffusion-webui-master\models\Stable-diffusion\furrydiffusion.ckpt
Traceback (most recent call last):
  File "D:\123\stable-diffusion-webui-master\launch.py", line 48, in <module>
    main()
  File "D:\123\stable-diffusion-webui-master\launch.py", line 44, in main
    start()
  File "D:\123\stable-diffusion-webui-master\modules\launch_utils.py", line 436, in start
    webui.webui()
  File "D:\123\stable-diffusion-webui-master\webui.py", line 64, in webui
    shared.demo = ui.create_ui()
  File "D:\123\stable-diffusion-webui-master\modules\ui.py", line 326, in create_ui
    scripts.scripts_txt2img.initialize_scripts(is_img2img=False)
  File "D:\123\stable-diffusion-webui-master\modules\scripts.py", line 436, in initialize_scripts
    script = script_data.script_class()
  File "D:\123\stable-diffusion-webui-master\extensions\lazy-pony-prompter\scripts\lpp_extension.py", line 76, in __init__
    self.lpp = LPP(base_dir)
  File "D:\123\stable-diffusion-webui-master\extensions\lazy-pony-prompter\lpp.py", line 13, in __init__
    self.__prompt_cache = self.__load_prompt_cache()
  File "D:\123\stable-diffusion-webui-master\extensions\lazy-pony-prompter\lpp.py", line 29, in __load_prompt_cache
    update_legacy_prompt_cache(self.__work_dir)
  File "D:\123\stable-diffusion-webui-master\extensions\lazy-pony-prompter\lpp_utils.py", line 62, in update_legacy_prompt_cache
    shutil.copy(cache_file, backup_file)
  File "C:\Users\danil\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\danil\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\123\\stable-diffusion-webui-master\\extensions\\lazy-pony-prompter\\cache.json'
Creating model from config: D:\123\stable-diffusion-webui-master\configs\v1-inference.yaml
Loading VAE weights specified in settings: D:\123\stable-diffusion-webui-master\models\VAE\kl-f8-anime.ckpt
Applying attention optimization: xformers... done.
Model loaded in 6.6s (load weights from disk: 1.3s, create model: 0.9s, apply weights to model: 1.4s, load VAE: 2.2s, move model to device: 0.1s, calculate empty prompt: 0.5s).
Для продолжения нажмите любую клавишу . . .`

3)Created an empty file "cache.json" in the root folder

`venv "D:\123\stable-diffusion-webui-master\venv\Scripts\Python.exe"
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.6.0
Commit hash: <none>
Launching Web UI with arguments: --xformers
Loading weights [0f885597eb] from D:\123\stable-diffusion-webui-master\models\Stable-diffusion\furrydiffusion.ckpt
Traceback (most recent call last):
  File "D:\123\stable-diffusion-webui-master\launch.py", line 48, in <module>
    main()
  File "D:\123\stable-diffusion-webui-master\launch.py", line 44, in main
    start()
  File "D:\123\stable-diffusion-webui-master\modules\launch_utils.py", line 436, in start
    webui.webui()
  File "D:\123\stable-diffusion-webui-master\webui.py", line 64, in webui
    shared.demo = ui.create_ui()
  File "D:\123\stable-diffusion-webui-master\modules\ui.py", line 326, in create_ui
    scripts.scripts_txt2img.initialize_scripts(is_img2img=False)
  File "D:\123\stable-diffusion-webui-master\modules\scripts.py", line 436, in initialize_scripts
    script = script_data.script_class()
  File "D:\123\stable-diffusion-webui-master\extensions\lazy-pony-prompter\scripts\lpp_extension.py", line 76, in __init__
    self.lpp = LPP(base_dir)
  File "D:\123\stable-diffusion-webui-master\extensions\lazy-pony-prompter\lpp.py", line 13, in __init__
    self.__prompt_cache = self.__load_prompt_cache()
  File "D:\123\stable-diffusion-webui-master\extensions\lazy-pony-prompter\lpp.py", line 29, in __load_prompt_cache
    update_legacy_prompt_cache(self.__work_dir)
  File "D:\123\stable-diffusion-webui-master\extensions\lazy-pony-prompter\lpp_utils.py", line 66, in update_legacy_prompt_cache
    cache_json = json.load(f)
  File "C:\Users\danil\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\danil\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\danil\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\danil\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Creating model from config: D:\123\stable-diffusion-webui-master\configs\v1-inference.yaml
Loading VAE weights specified in settings: D:\123\stable-diffusion-webui-master\models\VAE\kl-f8-anime.ckpt
Applying attention optimization: xformers... done.
Model loaded in 6.6s (load weights from disk: 1.3s, create model: 0.9s, apply weights to model: 1.4s, load VAE: 2.3s, move model to device: 0.1s, calculate empty prompt: 0.4s).
Для продолжения нажмите любую клавишу . . .`

**Comment by Siberpone** [comment]
Thank you for bringing this to my attention!

The issue should be fixed by 282ad36ce6f0b8da656bf70575bfe7472887bf48.

Reinstall the extension and it should start right up. Let me know if it worked for you.

**Comment by Krabbalka** [comment]
Yes, thanks, it works!
