### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 23189: character maps to <undefined>

### ISSUE THREAD

**Issue by joshilita** [Siberpone/lazy-pony-prompter#11]
Getting this error on both forge and comfyui (using stability matrix) 

`*** Error loading script: lpp_extension.py
    Traceback (most recent call last):
      File "C:\Users\josh\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\josh\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\josh\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions\lazy-pony-prompter\scripts\lpp_extension.py", line 93, in <module>
        lpp: LPP_A1111 = LPP_A1111(
      File "C:\Users\josh\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions\lazy-pony-prompter\lpp\ui\a1111.py", line 20, in __init__
        self.__sources: dict[str:TagSourceBase] = get_sources(self.__work_dir)
      File "C:\Users\josh\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions\lazy-pony-prompter\lpp\sources\utils.py", line 6, in get_sources
        return {x.__name__: x(work_dir) for x in TagSourceBase.__subclasses__()}
      File "C:\Users\josh\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions\lazy-pony-prompter\lpp\sources\utils.py", line 6, in <dictcomp>
        return {x.__name__: x(work_dir) for x in TagSourceBase.__subclasses__()}
      File "C:\Users\josh\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions\lazy-pony-prompter\lpp\sources\derpibooru.py", line 16, in __init__
        config = self._get_config()
      File "C:\Users\josh\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions\lazy-pony-prompter\lpp\sources\common.py", line 73, in _get_config
        config_entry = json.load(f)
      File "json\__init__.py", line 293, in load
      File "encodings\cp1252.py", line 23, in decode
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 23189: character maps to <undefined>`

The webui won't launch unless i manually delete extension.

**Comment by joshilita** [comment]
Nevermind, just realized my VM was set to the wrong region that didn't support UTF-8
