### ISSUE TITLE
Cannot start Webui after new install

### ISSUE THREAD

**Issue by PonyCrotTitLover** [Siberpone/lazy-pony-prompter#12]
Cannot start any Webui after installing the latest version of this extension

Error from auto1111
*** Error loading script: lpp_extension.py
    Traceback (most recent call last):
      File "D:\AI_Diffusion\= Dump\Image - Diffusion Backups\stable-diffusion-webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI_Diffusion\= Dump\Image - Diffusion Backups\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI_Diffusion\= Dump\Image - Diffusion Backups\stable-diffusion-webui\extensions\lazy-pony-prompter\scripts\lpp_extension.py", line 93, in <module>
        lpp: LPP_A1111 = LPP_A1111(
      File "D:\AI_Diffusion\= Dump\Image - Diffusion Backups\stable-diffusion-webui\extensions\lazy-pony-prompter\lpp\ui\a1111.py", line 20, in __init__
        self.__sources: dict[str:TagSourceBase] = get_sources(self.__work_dir)
      File "D:\AI_Diffusion\= Dump\Image - Diffusion Backups\stable-diffusion-webui\extensions\lazy-pony-prompter\lpp\sources\utils.py", line 6, in get_sources
        return {x.__name__: x(work_dir) for x in TagSourceBase.__subclasses__()}
      File "D:\AI_Diffusion\= Dump\Image - Diffusion Backups\stable-diffusion-webui\extensions\lazy-pony-prompter\lpp\sources\utils.py", line 6, in <dictcomp>
        return {x.__name__: x(work_dir) for x in TagSourceBase.__subclasses__()}
      File "D:\AI_Diffusion\= Dump\Image - Diffusion Backups\stable-diffusion-webui\extensions\lazy-pony-prompter\lpp\sources\derpibooru.py", line 16, in __init__
        config = self._get_config()
      File "D:\AI_Diffusion\= Dump\Image - Diffusion Backups\stable-diffusion-webui\extensions\lazy-pony-prompter\lpp\sources\common.py", line 73, in _get_config
        config_entry = json.load(f)
      File "C:\Users\UserBoo\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
        return loads(fp.read(),
      File "C:\Users\UserBoo\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 23189: character maps to <undefined>

---
Loading weights [67ab2fd8ec] from D:\AI_Diffusion\= Dump\Image - Diffusion Backups\stable-diffusion-webui\models\Stable-diffusion\BASEPony_PonyDiffusionV6XLv6.safetensors
Traceback (most recent call last):
  File "D:\AI_Diffusion\= Dump\Image - Diffusion Backups\stable-diffusion-webui\launch.py", line 48, in <module>
    main()
  File "D:\AI_Diffusion\= Dump\Image - Diffusion Backups\stable-diffusion-webui\launch.py", line 44, in main
    start()
  File "D:\AI_Diffusion\= Dump\Image - Diffusion Backups\stable-diffusion-webui\modules\launch_utils.py", line 469, in start
    webui.webui()
  File "D:\AI_Diffusion\= Dump\Image - Diffusion Backups\stable-diffusion-webui\webui.py", line 64, in webui
    shared.demo = ui.create_ui()
  File "D:\AI_Diffusion\= Dump\Image - Diffusion Backups\stable-diffusion-webui\modules\ui.py", line 1102, in create_ui
    settings.create_ui(loadsave, dummy_component)
  File "D:\AI_Diffusion\= Dump\Image - Diffusion Backups\stable-diffusion-webui\modules\ui_settings.py", line 161, in create_ui
    component = create_setting_component(k)
  File "D:\AI_Diffusion\= Dump\Image - Diffusion Backups\stable-diffusion-webui\modules\ui_settings.py", line 29, in create_setting_component
    args = info.component_args() if callable(info.component_args) else info.component_args
  File "D:\AI_Diffusion\= Dump\Image - Diffusion Backups\stable-diffusion-webui\extensions\lazy-pony-prompter\scripts\lpp_extension.py", line 44, in <lambda>
    lambda: {"choices": ["None"] + lpp.prompt_collections},
NameError: name 'lpp' is not defined

**Comment by Siberpone** [comment]
@PonyCrotTitLover Pushed a potential fix for this issue on https://github.com/Siberpone/lazy-pony-prompter/tree/12-win-config-encoding

Please, try to reinstall the extension through the "install from URL" tab, but additionally type in the "Specific branch name": `12-win-config-encoding` and let me know if that fixes the problem.

**Comment by PonyCrotTitLover** [comment]
> @PonyCrotTitLover Pushed a potential fix for this issue on https://github.com/Siberpone/lazy-pony-prompter/tree/12-win-config-encoding
> 
> Please, try to reinstall the extension through the "install from URL" tab, but additionally type in the "Specific branch name": `12-win-config-encoding` and let me know if that fixes the problem.

Yep, that seems to have fixed it. Loads and works fine now.

**Comment by Siberpone** [comment]
Splendid! I upstreamed the fix, so you should switch back to the `main` branch. You can do this either by reinstalling the extension once again, without any extra arguments, or by navigating to the extension's directory in the A1111 install location and running these commands in a terminal/cmd:
```
git checkout main
git pull
```
